/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.ufpe.cin.chat.view;

import java.awt.Color;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.JLabel;
import java.awt.Font;

/**
 *
 * @author Adilson
 */
public class PainelUsuario extends javax.swing.JPanel {


	private static final long serialVersionUID = -3270484269959487149L;
	public PainelUsuario(String nome, String IP, boolean logado) {

		initComponents(nome, IP, logado);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed" desc="Generated Code">                          
	private void initComponents(String nome, String IP, boolean logado) {

		progressoRecebimento = new javax.swing.JProgressBar();
		progressoEnvio = new javax.swing.JProgressBar();
		labelNome = new javax.swing.JLabel();
		labelIP = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();
		labelConexao = new javax.swing.JLabel();
		nomeUsuario = new javax.swing.JTextField();
		ipUsuario = new javax.swing.JTextField();

		progressoRecebimento.setForeground(new java.awt.Color(153, 87, 207));

		progressoEnvio.setForeground(new java.awt.Color(0, 153, 204));
		progressoEnvio.setEnabled(false);

		labelNome.setText("Nome");

		labelIP.setText("IP");

		jLabel3.setText("Envio para cliente");

		jLabel4.setText("Envio do cliente");

		jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
		jLabel5.setText("Conectado:");

		labelConexao.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
		labelConexao.setForeground(new java.awt.Color(0, 204, 51));
		labelConexao.setText("SIM");
		labelConexao.setToolTipText("");

		nomeUsuario.setEditable(false);

		ipUsuario.setEditable(false);

		JLabel lblNewLabel = new JLabel("Mensagem pendente:");
		lblNewLabel.setFont(new Font("Tahoma", Font.BOLD, 14));

		labelPendente = new JLabel();
		labelPendente.setToolTipText("");
		labelPendente.setText("N\u00C3O");
		labelPendente.setForeground(Color.RED);
		labelPendente.setFont(new Font("Tahoma", Font.BOLD, 14));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		layout.setHorizontalGroup(
				layout.createParallelGroup(Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addGroup(layout.createParallelGroup(Alignment.LEADING)
								.addGroup(layout.createSequentialGroup()
										.addContainerGap()
										.addGroup(layout.createParallelGroup(Alignment.TRAILING)
												.addComponent(labelIP, GroupLayout.PREFERRED_SIZE, 54, GroupLayout.PREFERRED_SIZE)
												.addComponent(labelNome, Alignment.LEADING, GroupLayout.PREFERRED_SIZE, 54, GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(ComponentPlacement.RELATED)
										.addGroup(layout.createParallelGroup(Alignment.LEADING, false)
												.addComponent(ipUsuario)
												.addComponent(nomeUsuario, GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)))
								.addGroup(layout.createSequentialGroup()
										.addGroup(layout.createParallelGroup(Alignment.TRAILING)
												.addGroup(layout.createSequentialGroup()
														.addGap(62)
														.addGroup(layout.createParallelGroup(Alignment.LEADING, false)
																.addComponent(jLabel3, GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
																.addComponent(jLabel4, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
																.addComponent(jLabel5, GroupLayout.PREFERRED_SIZE, 109, GroupLayout.PREFERRED_SIZE)))
												.addGroup(layout.createSequentialGroup()
														.addContainerGap()
														.addComponent(lblNewLabel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
										.addPreferredGap(ComponentPlacement.RELATED)
										.addGroup(layout.createParallelGroup(Alignment.LEADING)
												.addComponent(labelPendente, GroupLayout.PREFERRED_SIZE, 73, GroupLayout.PREFERRED_SIZE)
												.addComponent(labelConexao, GroupLayout.PREFERRED_SIZE, 73, GroupLayout.PREFERRED_SIZE)
												.addComponent(progressoRecebimento, GroupLayout.PREFERRED_SIZE, 167, GroupLayout.PREFERRED_SIZE)
												.addComponent(progressoEnvio, GroupLayout.PREFERRED_SIZE, 167, GroupLayout.PREFERRED_SIZE))))
						.addContainerGap(60, Short.MAX_VALUE))
				);
		layout.setVerticalGroup(
				layout.createParallelGroup(Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addGap(11)
						.addGroup(layout.createParallelGroup(Alignment.BASELINE)
								.addComponent(labelNome, GroupLayout.PREFERRED_SIZE, 25, GroupLayout.PREFERRED_SIZE)
								.addComponent(nomeUsuario, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
						.addGap(1)
						.addGroup(layout.createParallelGroup(Alignment.BASELINE)
								.addComponent(labelIP)
								.addComponent(ipUsuario, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
						.addGap(75)
						.addGroup(layout.createParallelGroup(Alignment.BASELINE)
								.addComponent(labelPendente, GroupLayout.PREFERRED_SIZE, 52, GroupLayout.PREFERRED_SIZE)
								.addComponent(lblNewLabel, GroupLayout.PREFERRED_SIZE, 37, GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(ComponentPlacement.RELATED)
						.addGroup(layout.createParallelGroup(Alignment.BASELINE)
								.addComponent(jLabel5, GroupLayout.PREFERRED_SIZE, 52, GroupLayout.PREFERRED_SIZE)
								.addComponent(labelConexao, GroupLayout.PREFERRED_SIZE, 52, GroupLayout.PREFERRED_SIZE))
						.addGap(31)
						.addGroup(layout.createParallelGroup(Alignment.LEADING)
								.addComponent(jLabel3, GroupLayout.PREFERRED_SIZE, 30, GroupLayout.PREFERRED_SIZE)
								.addComponent(progressoEnvio, GroupLayout.PREFERRED_SIZE, 31, GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(ComponentPlacement.RELATED)
						.addGroup(layout.createParallelGroup(Alignment.LEADING)
								.addComponent(jLabel4, GroupLayout.PREFERRED_SIZE, 30, GroupLayout.PREFERRED_SIZE)
								.addComponent(progressoRecebimento, GroupLayout.PREFERRED_SIZE, 31, GroupLayout.PREFERRED_SIZE))
						.addContainerGap(24, Short.MAX_VALUE))
				);
		this.setLayout(layout);


		this.nomeUsuario.setText(nome);
		this.ipUsuario.setText(IP);
		if(logado){
			this.labelConexao.setText("SIM");
			this.labelConexao.setForeground(new Color(0, 204, 51));
		}else{
			this.labelConexao.setText("NÃO");
			this.labelConexao.setForeground(Color.red);
		}

	}// </editor-fold>                        


	// Variables declaration - do not modify                     
	private javax.swing.JTextField ipUsuario;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel labelIP;
	private javax.swing.JLabel labelNome;
	private javax.swing.JTextField nomeUsuario;
	private javax.swing.JProgressBar progressoEnvio;
	private javax.swing.JProgressBar progressoRecebimento;
	private javax.swing.JLabel labelConexao;
	private JLabel labelPendente;
	// End of variables declaration                   

	public javax.swing.JTextField getIpUsuario() {
		return ipUsuario;
	}

	public javax.swing.JTextField getNomeUsuario() {
		return nomeUsuario;
	}

	public javax.swing.JProgressBar getProgressoEnvio() {
		return progressoEnvio;
	}

	public javax.swing.JProgressBar getProgressoRecebimento() {
		return progressoRecebimento;
	}

	public javax.swing.JLabel getLabelConexao() {
		return labelConexao;
	}

	public void setPendente(boolean pendente){
		if (pendente){
			labelPendente.setText("SIM");
			labelPendente.setForeground(new java.awt.Color(0, 204, 51));
		}
		else{
			labelPendente.setText("NÃO");
			labelPendente.setForeground(Color.RED);
		}
	}

	public void setConectado(boolean conectado){
		if (conectado){
			labelConexao.setText("SIM");
			labelConexao.setForeground(new java.awt.Color(0, 204, 51));
		}
		else{
			labelConexao.setText("NÃO");
			labelConexao.setForeground(Color.RED);
		}
	}
}
